annotations:
  paths:
    - data/llm_reference.csv

anchors:
  comment_scores_path: facets/human_baseline/human_facets_scores.1.txt
  item_scores_path: facets/human_baseline/human_facets_scores.3.txt

output:
  facets_run_dir: facets/llm_severities
  facets_data_filename: llm_severities_data.tsv
  facets_spec_filename: llm_severities_spec.txt
  facets_score_filename: llm_severities_scores.txt
  facets_output_filename: llm_severities_output.txt

facets:
  title: MHS Reference Set LLMs Anchored To Human Baseline
  model: "?, ?, #, R"
  noncenter: 2
  positive: 1
  arrange: N
  subset_detection: No
  delements:
    - 1N
    - 2N
    - 3N
  csv: Tab
